// Embed the built widget (single inlined HTML file) into core as a TS module string,
// so addCharts can serve it as the ui:// resource. Run after building the widget.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const widgetHtml = join(here, "..", "..", "widget", "dist", "index.html");
const outDir = join(here, "..", "src", "generated");
const out = join(outDir, "widget-html.ts");

if (!existsSync(widgetHtml)) {
  console.error(
    `[embed-widget] ${widgetHtml} not found. Build the widget first ` +
      `(run \`pnpm build\` from the repo root, which builds the widget before core). ` +
      `Refusing to build core against a stale/missing widget.`,
  );
  process.exit(1);
}

const html = readFileSync(widgetHtml, "utf8");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/embed-widget.mjs — do not edit.\nexport const WIDGET_HTML = ${JSON.stringify(html)};\n`,
);
console.error(`[embed-widget] wrote ${out} (${(html.length / 1024).toFixed(1)} KB)`);
